=== gukkray/atividades-pos-2024/xml/definicoes.dtd
<!ELEMENT cardapio (prato+)>
<!ELEMENT prato (nome, descricao, ingredientes, preco, calorias, tempodePreparo)>
<!ATTLIST prato id ID #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT tempodePreparo (#PCDATA)>

=== gukkray/atividades-pos-2024/xml/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cardapio SYSTEM "definicoes.dtd">

<cardapio>
    <prato id="dp01">
        <nome>Pudim</nome>
        <descricao>Pudim de leite</descricao>
        <ingredientes>
            <ingrediente>
                açúcar
            </ingrediente>
            <ingrediente>
                leite condensado
            </ingrediente>
            <ingrediente>
                Leite
            </ingrediente>
            <ingrediente>
                ovo
            </ingrediente>
        </ingredientes>
        <preco>40 reais</preco>
        <calorias>750 kcal</calorias>
        <tempodePreparo>40 minutos</tempodePreparo>
    </prato>
    <prato id="dp02">
        <nome>Lasanha à Bolonhesa</nome>
        <descricao>Camadas de massa intercaladas com molho de carne moída à bolonhesa e queijo</descricao>
        <ingredientes>
            <ingrediente> para lasanha</ingrediente>
            <ingrediente>carne moída</ingrediente>
            <ingrediente>tomate</ingrediente>
            <ingrediente>queijo mozarela</ingrediente>
            <ingrediente>queijo parmesão</ingrediente>
        </ingredientes>
        <preco>22 reais</preco>
        <calorias>450 kcal</calorias>
        <tempodePreparo>60 minutos</tempodePreparo>
    </prato>
    
    <prato id="dp03">
        <nome>Frango à Parmegiana</nome>
        <descricao>Peito de frango empanado e frito, coberto com molho de tomate e queijo derretido</descricao>
        <ingredientes>
            <ingrediente>Peito de frango</ingrediente>
            <ingrediente>farinha de rosca</ingrediente>
            <ingrediente>ovos</ingrediente>
            <ingrediente>molho de tomate</ingrediente>
            <ingrediente>queijo mozarela</ingrediente>
            <ingrediente>queijo parmesão</ingrediente>
        </ingredientes>
        <preco>18 reais</preco>
        <calorias>380 kcal</calorias>
        <tempodePreparo>50 minutos</tempodePreparo>
    </prato>
    <prato id="dp04">
        <nome>Massa Carbonara</nome>
        <descricao>Massa italiana com molho à base de ovos, queijo parmesão, pancetta e pimenta preta</descricao>
        <ingredientes>
            <ingrediente>Massa tipo spaghetti</ingrediente>
            <ingrediente>ovos</ingrediente>
            <ingrediente>queijo parmesão</ingrediente>
            <ingrediente>pancetta</ingrediente>
            <ingrediente>pimenta preta</ingrediente>
        </ingredientes>
        <preco>20 reais</preco>
        <calorias>400 kcal</calorias>
        <tempodePreparo>30 minutos</tempodePreparo>
    </prato>
    <prato id="dp05">
        <nome>Sushi Combo</nome>
        <descricao>Seleção variada de sushis e sashimis, acompanhados de molho de soja e wasabi</descricao>
        <ingredientes>
            <ingrediente>Arroz de sushi</ingrediente>
            <ingrediente>peixes variados</ingrediente>
            <ingrediente>nori</ingrediente>
            <ingrediente>molho de soja</ingrediente>
            <ingrediente>wasabi</ingrediente>
        </ingredientes>
        <preco>30 reais</preco>
        <calorias>350 kcal</calorias>
        <tempodePreparo>45 minutos</tempodePreparo>
    </prato>
</cardapio>

<!-- nome,descricao,ingredientes,preco,calorias,tempodepreparo -->
